### ISSUE TITLE
CLI with configuration file never stops

### ISSUE THREAD

**Issue by tribouille** [EasyinnovaSL/DPFManager#133]
Hi,

I am using the file http://78.108.103.11/MIRROR/ftp/tiff-samples/tiger-75-rgb-jpg.tiff
(First TIFF image I got doing "indexof: tiff" in google...)

I am using the following configuration file:
```
$cat /tmp/DPFConfig.dpf 
ISO     Baseline
ISO     Tiff/EP
ISO     Tiff/IT
ISO     Tiff/IT-1
ISO     Tiff/IT-2
FORMAT  XML
OUTPUT  /tmp/test
```

When I execute DPF Manager (latest release), the parsing/checking is done but the CLI is not stopping using a configuration file.

I tried on Ubuntu 15.10 and Debian testing.

What I did exactly:
```
cd /tmp
wget http://78.108.103.11/MIRROR/ftp/tiff-samples/tiger-75-rgb-jpg.tiff
DPFManager -configuration /tmp/DPFConfig.dpf /tmp/tiger-75-rgb-jpg.tiff
```
Here, it never quits.

I have to kill it in another shell.
When I check in the output directory, the report is here.
```
ls /tmp/test/
1-tiger-75-rgb-jpg.tiff.xml  summary.xml
```
Do you need more information to reproduce?
Thanks,

PS: I also tried with the version of the branch (https://github.com/EasyinnovaSL/DPFManager/tree/JacpFX)

**Comment by victormunoz** [comment]
Hello,
Thank you for the feedback!
We have been able to reproduce the problem. It only happens in Linux systems. Once the report is generated the application tries to open it, but in Linux this doesn't work.
You can avoid this problem by using the "silence" option (-s) that will not try to open the report at the end.
However we are going to fix this in the next release.
Thanks again,

**Comment by tribouille** [comment]
Hi,

thank you for your quick answer.
I confirm with the -s it's working.

> Once the report is generated the application tries to open it
Does this mean you should print the report on the output?
(I don't have access to a Windows/Mac computer right now to test)

Thanks,

**Comment by victormunoz** [comment]
Without the -s option, the application tries to open the generated report with the default system application of the specified format.

If you generate a PDF report, then the CLI automatically tries to open the report with the default PDF reader, if you generate an HTML report, the default browser is opened to show it, etc.
