### ISSUE TITLE
DMG Image not recognized

### ISSUE THREAD

**Issue by verwinv** [EasyinnovaSL/DPFManager#152]
Hi, tried to install the DMG from http://dpfmanager.org/ but received the message that the image couldn't be opened. 

![screenshot 2016-04-05 15 14 28](https://cloud.githubusercontent.com/assets/6201005/14282946/413abd34-fb41-11e5-8b54-d48971cfbcce.png)

**Comment by victormunoz** [comment]
Hello, we apologize for the inconvenience. It seems the file was not correctly uploaded to the server.
We have reuploaded it again, and now it works.
Many thanks for informing us about this!

**Comment by verwinv** [comment]
Thanks Victor!
