### ISSUE TITLE
Importing a corrupted configuration file fails too late

### ISSUE THREAD

**Issue by cweigel** [EasyinnovaSL/DPFManager#251]
Version: 2.4
OS: Windows

I intentionally corrupted the configuration XML. After that the import of that file "succeeds" and the format error pops up only when trying to edit or to check files. The xml check and thus the error should **immediately show up on importing** not leaving and non-functional entry... (see below):

![dpf_manager_non_functional_config](https://cloud.githubusercontent.com/assets/13655319/18050978/2474c6da-6df2-11e6-8c68-8e0c2318051c.png)

**Comment by victormunoz** [comment]
Thank you for your comments! We will solve the bugs and make the improvements in future releases.
