### ISSUE TITLE
working with windows-executable version 2.4: Drag and drop a file or folder would be nice to have

### ISSUE THREAD

**Issue by StefanRohde-Enslin** [EasyinnovaSL/DPFManager#254]
Just a suggestion: I think the possiblity to drag-and-drop files or folders somewhere for further processing (upload, check ...) is meanwhile what people expect. It would be very helpful to have this implemented into the dpf-manager files-selection.

**Comment by victormunoz** [comment]
It's a good idea. Thank you!
