### ISSUE TITLE
working with windows-executable version 2.4: "Select button, submenu" not working

### ISSUE THREAD

**Issue by StefanRohde-Enslin** [EasyinnovaSL/DPFManager#256]
When I click on the triangle located in the "select"-button of the start part a black area is displayed below, the pointer turns into a wheel and the program freezes.
Might be the same reason as for issue 253 ?

**Comment by victormunoz** [comment]
Yes it seems to be the same issue, related to the displaying of context menus in some OS.

**Comment by victormunoz** [comment]
We have been unable to reproduce this error.
Can you tell us exactly which OS version, and Java version, are you using?
Also, you could try with the newest DPF Manager version 2.6
