### ISSUE TITLE
v2.4 GUI / UX # Could be more compact, e.g., the DPF Manager logo occupies a huge chunk.

### ISSUE THREAD

**Issue by beyo-ra** [EasyinnovaSL/DPFManager#261]
Comment
The GUI could be more, um, compact, currently it initially takes a rather large space.

**Comment by victormunoz** [comment]
![newgui](https://cloud.githubusercontent.com/assets/12271074/18270084/6557508e-742b-11e6-9926-24d880dfd1ec.png)

**Comment by beyo-ra** [comment]
I should have put a question mark after my statement...

Personally i think the layout has improved, and the logo could be further compacted... :)  This is of course a matter of preference, and I am just sharing mine.

As a side note. I like e.g. what yo have done with the console and tasks expandable and collapsible windows.

**Comment by victormunoz** [comment]
We agreed with your opinion. And so we changed it. We thought on the possibility to put the logo in the upper left corner, or even remove it at all, but for now the chosen option has been this one.
Thank you again for your comments!
