### ISSUE TITLE
v2.4 CLI # So slooooow.

### ISSUE THREAD

**Issue by beyo-ra** [EasyinnovaSL/DPFManager#262]
Running DPFManager -help responds in ~2s.
Other commands, such as, DPFManager -v responds in ~3s.

**Comment by victormunoz** [comment]
Actually, the application loads also the javafx framework even in CLI mode, that's why it's slow...

**Comment by beyo-ra** [comment]
I would agree with you that ease of development should have precedent, however,

I would argue that how a software responds to a user's action, generally relates to how the user perceives the quality of the software. I primarily base this conclusion on anecdotal evidence regarding web sites or web applications, but the principle should hold true for desktop applications.

I would argue that the CLI is expected to respond quickly and a slow response would be interpreted as erroneous; most likely in the code or in, this case, the interpreter--Java.

**Comment by victormunoz** [comment]
In the last updates we have focused the efficiency improvements in the tiff conformance checking process. However we hope also to improve the startup time in next releases.

**Comment by beyo-ra** [comment]
Please see/cf https://github.com/veraPDF/veraPDF-apps/issues/61

**Comment by victormunoz** [comment]
We have improved the response time of these commands for the next release.
