### ISSUE TITLE
v2.4 CLI # Remote check options: -url <url:port>

### ISSUE THREAD

**Issue by beyo-ra** [EasyinnovaSL/DPFManager#263]
Currently:

    riksarkivet.se/tiff:80

A more appropriate format would be:

    <scheme:[//[user:password@]host[:port]][/]path>

As in https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax

     scheme:[//[user:password@]host[:port]][/]path[?query][#fragment]

E.g.

    riksarkivet.se:80/tiff

I do not know what URI parser you are using, but staying close to the standard format of URI would be recommended.

**Comment by victormunoz** [comment]
Ok, we will take it into account for future updates. Thanks

**Comment by Adri7** [comment]
We always used the standard format of URI, we accept URLs like your example (riksarkivet.se:80/tiff).
Recently we changed the input parameters and also the help messages. Now the description of '--url' parameter is clearer.
