### ISSUE TITLE
v2.4 DOC # dpf_manager -> DPFManager?

### ISSUE THREAD

**Issue by beyo-ra** [EasyinnovaSL/DPFManager#265]
The document refers to dpf_manager, however,

v2.4 seem to have renamed the binary, and directories, to DPFManager, see e.g.,
- http://www.dpfmanager.org/documentation.html
- http://www.dpfmanager.org/Downloads/User%20Manual.pdf

**Comment by victormunoz** [comment]
Yes, we are going to update the docs. Thank you!

**Comment by nkrabben** [comment]
The documentation should also include instructions on creating an alias for CLI usage
`alias dpf_manager="/Applications/DPF\ Manager.app/Contents/MacOS/DPF\ Manager"`
