### ISSUE TITLE
"online validator" permanently throws "error"

### ISSUE THREAD

**Issue by StefanRohde-Enslin** [EasyinnovaSL/DPFManager#285]
Tried it with several files ... whenever I choose a configuration, selected a file for upload and than clicked on Check ... I get an error message called "Error. Server error!"

**Comment by victormunoz** [comment]
Can you tell me which OS and navigator are you using?

**Comment by StefanRohde-Enslin** [comment]
Tried it in Firefox 48.0.2 on Windows7 and in IE11. Nothing did work.
BUT: Tried it today (FF48/Win7) and it works. Magic ...

**Comment by victormunoz** [comment]
Ok, I guess it was a punctual connection problem with server
