### ISSUE TITLE
DPF Manager 3.0 Uninstall does not remove all files (Windows 7)

### ISSUE THREAD

**Issue by cweigel** [EasyinnovaSL/DPFManager#322]
When uninstalling DPFManager 3.0 (Windows 7) not all files get remove although answering the question to remove all reports and profiles with "yes".

Remaining in "Program Files":

    C:\Program Files\DPF Manager>tree /f
    Auflistung der Ordnerpfade für Volume SPEEDY
    Volumeseriennummer : DC88-EAE1
    C:.
    +---app
        ¦   nullsummary.xml
        ¦
        +---html
            +---css
            ¦       bootstrap.css
            ¦       default.css
            ¦       font-awesome.css
            ¦       fontello.css
            ¦
            +---fonts
            ¦       fontawesome-webfont.eot
            ¦       fontawesome-webfont.svg
            ¦       fontawesome-webfont.ttf
            ¦       fontawesome-webfont.woff
            ¦       fontawesome-webfont.woff2
            ¦       FontAwesome.otf
            ¦       fontello.eot
            ¦       fontello.svg
            ¦       fontello.ttf
            ¦       fontello.woff
            ¦       fontello.woff2
            ¦       Roboto-Bold.ttf
            ¦
            +---img
            ¦       check_radio_sheet.png
            ¦       logo - copia.png
            ¦       logo.png
            ¦       noise.jpg
            ¦
            +---js
                    bootstrap.min.js
                    jquery-1.9.1.min.js
                    jquery.flot.min.js
                    jquery.flot.pie.min.js

Remaining in user dir (even pretty old ones are there):

    C:\Users\wgl\DPF Manager>dir
     Datenträger in Laufwerk C: ist SPEEDY
     Volumeseriennummer: DC88-EAE1
    
     Verzeichnis von C:\Users\wgl\DPF Manager
    
    15.11.2016  10:13    <DIR>          .
    15.11.2016  10:13    <DIR>          ..
    15.11.2016  10:20               540 cweigel01.dpf
    15.11.2016  10:27    <DIR>          data
    15.11.2016  10:12    <DIR>          isos
    15.11.2016  10:14    <DIR>          reports
    29.08.2016  12:23    <DIR>          server
                   1 Datei(en),            540 Bytes
                   6 Verzeichnis(se), 18.679.017.472 Bytes frei

**Comment by victormunoz** [comment]
Yes, there is an issue here. We are going to fix the uninstallation script. Thanks for your comment!
