### ISSUE TITLE
Not possible to manage policies without GUI

### ISSUE THREAD

**Issue by kjadeglans** [EasyinnovaSL/DPFManager#335]
Managing policies requires a graphical environment and thus does not work in a non-graphical system.

**Environment**

DPF Manager version 3.0
openjdk version "1.8.0_111"
OS: Ubuntu 16.04.1 LTS 64-bit (headless, no GUI)

**Comment by victormunoz** [comment]
The next monthly release (at the end of this month) will include the functionality to create configuration files files through the command line.
