### ISSUE TITLE
Communications Error

### ISSUE THREAD

**Issue by nvanderperren** [EasyinnovaSL/DPFManager#336]
Terminal gives a communicatons Error. Probably initiated by generating periodical check?

`2016-11-30 15:36:08.366 DPF Manager[9256:320088] Communications error: <OS_xpc_error: <error: 0x7fff71463b90> { count = 1, contents =
	"XPCErrorDescription" => <string: 0x7fff71463f40> { length = 22, contents = "Connection interrupted" }
}>
Got xpc error message: Connection interrupted
`

Environment
DPF Manager version 3.0
jdk 1.8.0_111
OSX El Capitan v. 10.11.16
TIFF file: 29,9MB

**Comment by victormunoz** [comment]
Can you specify which command did you execute to get this error?

**Comment by victormunoz** [comment]
We have found a bug with the periodical checks in Mac, that could be related to this. Hopefully it will be fixed in the next release

**Comment by nvanderperren** [comment]
ok, it happened several minutes after I've saved a periodical check.
