### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by kjadeglans** [EasyinnovaSL/DPFManager#337]
Testing a folder with many files (1000 files) ends with:
**_"ERROR - An error occurred. Out of memory"_**
when creating individual reports.

Only 688 individual reports were listed as created. No actual reports created at all.

**Comment by kjadeglans** [comment]
Additional info: Testing another folder with 1000 files also ends with "out of memory" after all 1000 individual reports were listed.

However NO reports exist at all.

**Comment by victormunoz** [comment]
Is this issue solved?

**Comment by kjadeglans** [comment]
I must have closed this one by mistake. Sorry.

**Comment by victormunoz** [comment]
This problem will be solved in the next release at the end of this month
