### ISSUE TITLE
No reports in HTML when we have pretty files

### ISSUE THREAD

**Issue by Soniettte** [EasyinnovaSL/DPFManager#338]
With a deffault configuration.

Has this to be expected?

**Comment by victormunoz** [comment]
No, this should not happen. The "default" configuration should generate XML, METS and HTML reports.
Did any error message appear in the console?
PS. What do you mean by "pretty" files?

**Comment by Soniettte** [comment]
In the console I obtain this error:
WARN  - File G:\DOC_01\Test-PREFORMA\Manuals\100\Thumbs.db is not an accepted format

As I checked it happens when I check with 100 or 1000 files.

**Comment by victormunoz** [comment]
This is not a "error", it is just a warning (warn) to inform the files which are not Tiffs (and thus are ignored) from the folder you specified.
But this message should not be related to the issue. Are the HTML reports still not being generated? Does this only happen with the default config?

**Comment by Soniettte** [comment]
When I check 100 files HTML report is not generated with default configuration.  But with a Baseline HTML configuration I obtain the HTML report.
Otherwise when I check 10 files HTML report is generated with default configuration.

**Comment by victormunoz** [comment]
Ok. We have been able to reproduce the issue.
It happens when some file in the folder is not TIFF.
We are going to fix this in the next release.
Thank you very much for notifying this!
