### ISSUE TITLE
WARN/ASK before overwriting reports with CLI tool

### ISSUE THREAD

**Issue by cweigel** [EasyinnovaSL/DPFManager#343]
When running a `dpf-manager-console` check on the same file with the same non-default directory the but with a different configuration the results just get overwritten. It should be asked before if that should be done. I recognized that in the User dir **all the reports** are kept by simply enumerate each run.  Would that be a strategy for the output dir?

**Comment by victormunoz** [comment]
Yes, one of the alternatives you proposed should be taken. Thanks for raising this
