### ISSUE TITLE
GUI freezes when adding a rule to the policy checker

### ISSUE THREAD

**Issue by bert-packed** [EasyinnovaSL/DPFManager#350]
Hi,

Trying to make a policy profile for my tiff files in DPF Manager 3.0 on Windows 10 and JAVA8.
When I tick the list box, I get a black contour of the list and the window freezes:
![image](https://cloud.githubusercontent.com/assets/5360065/20928779/9e051752-bbc7-11e6-8d1a-966b50a9751b.png)

bert

**Comment by victormunoz** [comment]
This issue seems to be related with #334 which should have been fixed in version 3.0.1

**Comment by victormunoz** [comment]
ok, it seems to be so
