### ISSUE TITLE
periodical checker checks only during weekdays

### ISSUE THREAD

**Issue by nvanderperren** [EasyinnovaSL/DPFManager#351]
It seems that the periodical checker only checks during weekdays and not during weekends (see pic). I used the GUI to set the periodical check daily. 

(and also, where can I find the report?  It's not in the report folder nor under the report tab in the GUI).

<img width="974" alt="schermafbeelding 2016-12-06 om 17 02 36" src="https://cloud.githubusercontent.com/assets/17183054/20933301/eeb4c4ee-bbd7-11e6-848f-16a1197d0fba.png">

**Comment by victormunoz** [comment]
Firstly, there is a bug with the cron task generated by the periodical checker, that in Mac OS it is not correctly created (the executable is not dpf-manager but "/Applications/DPF\ Manager.app/Contents/MacOS/DPF\ Manager").
This bug will be solved in the next release (at the end of this month).
Related issue: https://github.com/EasyinnovaSL/DPFManager/issues/336

Secondly, regarding the weekends, if the problem persists aslo with the new version, please post the cron tasks list (crontab -l).
