### ISSUE TITLE
Linux buildenv 3.1 (30 December 2016) # maven/bin/mvn: /bin/sh^M : bad interpreter

### ISSUE THREAD

**Issue by beyo-ra** [EasyinnovaSL/DPFManager#370]
The maven/bin/mvn shell script, and some other random sampled files in the bin directory apply control characters CR+LF (Windows/DOS) and not LF (UNIX) for newlines.

**Comment by victormunoz** [comment]
Ok. We will fix it. Thank you

**Comment by victormunoz** [comment]
You can find new build zips in the "Core Release" (dated 18-01-2017) which include an updated maven.
Also we have made some modifications and added an instructions file for help.
Hope the process is more clear now.
