### ISSUE TITLE
gui freeze when defining a policy check

### ISSUE THREAD

**Issue by bert-packed** [EasyinnovaSL/DPFManager#372]
Hi, 

Testing DPF 3.1 on windows 10 and when I open the drop-down list to select a parameter, the application freezes. 

![image](https://cloud.githubusercontent.com/assets/5360065/22554450/5932a358-e960-11e6-961b-ea6e40a27d0f.png)

thanks for looking into this'
bert

**Comment by bert-packed** [comment]
something similar happens when adding a fix:
![image](https://cloud.githubusercontent.com/assets/5360065/22555018/9212f680-e962-11e6-9005-8e2c688e1c09.png)

**Comment by victormunoz** [comment]
This issue seems to be related with #334 #256 and #253 
I thought all the dropdows now worked well, but seems that some of them still need the fix.
Thanks for reporting it!

**Comment by bert-packed** [comment]
Thanks for the quick reply!
Let me know when it is fixed, because I would like to test the policy and fixes functionality using the GUI with real life users and for the moment that is not feasible. 

Kind regards
Bert

**Comment by victormunoz** [comment]
I have created a hotfix for this.
You can download it only at our website (not in the open source portal): [http://dpfmanager.org/index.html#download](http://dpfmanager.org/index.html#download)
Please confirm me it has been fixed.
Thanks!

**Comment by bert-packed** [comment]
Hi Victor,

Installed 3.1.1 and managed to proceed to fields further before receiving the same error: 
![image](https://cloud.githubusercontent.com/assets/5360065/22592945/7421a99a-ea1c-11e6-90bf-8517d99ee970.png)

We're making progress ;)
Bert

**Comment by victormunoz** [comment]
I think I have finally found a definitive solution for this problem.
Can you try again downloading the installer from our website?

**Comment by bert-packed** [comment]
Hi Victor,
downloaded v3.1.1 with JVM but received an error message when the application launches: Failed to launch JVM.
bert

**Comment by victormunoz** [comment]
Ok...
Can you try once again now?
[http://www.blueroominnovation.com/dpfmanager/Downloads/Current-release/Windows/dpf_manager-3.1.1.exe](http://www.blueroominnovation.com/dpfmanager/Downloads/Current-release/Windows/dpf_manager-3.1.1.exe)

**Comment by bert-packed** [comment]
Hi Victor,

thanks for the quick reply. Application launches and adding policy rules works!
We continue testing in the coming days.
Thanks!
bert

**Comment by victormunoz** [comment]
Fantastic!
Thank you very much for testing and giving us feedback!
