### ISSUE TITLE
no check on policy rules

### ISSUE THREAD

**Issue by nvanderperren** [EasyinnovaSL/DPFManager#373]
Hello, DPF Manager doesn't seem to check on the policies in the policy checker. I've added that bit depth should be 64 and JPEG compression, but I've got no warning in the report while the bit depth of the files was 32 and uncompressed.

[metadata_AMVK.xlsx](https://github.com/EasyinnovaSL/DPFManager/files/748050/metadata_AMVK.xlsx)
<img width="620" alt="schermafbeelding 2017-02-02 om 15 55 25" src="https://cloud.githubusercontent.com/assets/17183054/22554367/1098076e-e960-11e6-8a80-674311464152.png">

**Comment by victormunoz** [comment]
Hello, in the case of warnings, they are reported when the condition is satisfied.
So in this example, a warning will appear in the report when an image has a BitDepth of 64 bits, or a JPEG compression.
