### ISSUE TITLE
"Error in input path" message in CLI mode

### ISSUE THREAD

**Issue by bitsgalore** [EasyinnovaSL/DPFManager#377]
I tried to analyze a few TIFFs with DPFManager 3.1.1 (using the Ubuntu Deb on Linux Mint). As an example, try the file below:

<https://github.com/openpreserve/format-corpus/blob/master/tiff-examples/NANETH_8bpp_grayscale/grayscale_8bpp_wrong_bpptag.tif?raw=true>

I used the following command:

    dpf-manager check grayscale_8bpp_wrong_bpptag.tif
    
Result:

    Conformance checker: TIFF conformance checker
    Extensions: tiff, tif
    Standard: TIFF/IT (TIFF/IT)
    Standard: TIFF/IT-P2 (TIFF/IT-P2)
    Standard: Extended TIFF 6.0 (Extended TIFF 6.0)
    Standard: TIFF/IT-P1 (TIFF/IT-P1)
    Standard: TI/A Draft (TI/A Draft)
    Standard: TIFF/EP (TIFF/EP)
    Standard: Baseline TIFF 6.0 (Baseline TIFF 6.0)

    ERROR - Error in input path grayscale_8bpp_wrong_bpptag.tif

So something went wrong, but it's not clear *what*. If I analyse the same file with the GUI, the output gives me the reasons why the file fails to validate:

    STRIPS-0003	IFD1	Image width and image height do not match with strips sizes
    TAG-284-0005	IFD1	PlanarConfiguration is irrelevant if SamplesPerPixel is 1, and need not be included.

So it seems something goes wrong in CLI mode.

**Comment by victormunoz** [comment]
Hello and thank you for giving us feedback!
In CLI mode you must specify the full path of the files to check.
However, this error message could be more explicative...

**Comment by bitsgalore** [comment]
Hi Victor,

Thanks. I'm wondering why the full path is needed in CLI mode? This isn't very intuitive and seems rather at odds with conventions of CLI tools in general.

**Comment by victormunoz** [comment]
Yes, we know... This is an open issue: #201
