### ISSUE TITLE
Remember path on file dialogs

### ISSUE THREAD

**Issue by cweigel** [EasyinnovaSL/DPFManager#38]
It would be a nice feature, if the file dialog windows would remember the latest path used (during the app is running but also in between separate runs)

**Comment by cweigel** [comment]
It might have to do with the following warning appearing sometimes:

    WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.

**Comment by victormunoz** [comment]
Yes it is a useful feature, we are going to make it. Thanks!
