### ISSUE TITLE
Installation problem on Windows 7

### ISSUE THREAD

**Issue by verwinv** [EasyinnovaSL/DPFManager#389]
At the Padua workshop, one person has the following installation problem - the system saying the software isn't compatible with her Windows version:

![2017-03-10 09 51 54](https://cloud.githubusercontent.com/assets/6201005/23788624/9cd65a2c-0577-11e7-9450-5e8d67822f6f.jpg)

**Comment by victormunoz** [comment]
Yes. There seems to be a problem with 32 bit machines.
We will solve it in the next release.

A workaround for now is to go to the "app" folder and run 
`java -jar "DPF Manager.exe"`

**Comment by victormunoz** [comment]
New 32bit installers have been created in the new release 3.2.
