### ISSUE TITLE
CLI reportformat option obsolete when using config file

### ISSUE THREAD

**Issue by cweigel** [EasyinnovaSL/DPFManager#39]
It seems, that the format configured in a configuration file  overrides the format given to the CLI using the `-reportformat` option. This renders the option obsolete.

**Comment by victormunoz** [comment]
Yes you are right. This option is not used any more (since the configuration files where introduced).
In the redesign phase we are going to define a new set of options for the command line (also for generating new configuration files via CLI, etc).
