### ISSUE TITLE
Process freeze with metadata fixer checked

### ISSUE THREAD

**Issue by verwinv** [EasyinnovaSL/DPFManager#392]
On a macbook, if you select metadata fixer boxes 2 and 3 together with a policy rule, the process freezes.

**Comment by victormunoz** [comment]
Ok, thank you for your feedback.
We will investigate it and fix for the next release

**Comment by victormunoz** [comment]
Sorry we have not been able to reproduce this issue.
Can you send us the file and configuration that produces this bug?

**Comment by victormunoz** [comment]
A new version of DPF Manager has been released.
I am going to close this issue, but please reopen it if the problem persists.
Thank you!

**Comment by victormunoz** [comment]
Finally we have reproduced this problem. It will be solved in the next release.
