### ISSUE TITLE
Feature request: Clarify policy creation

### ISSUE THREAD

**Issue by verwinv** [EasyinnovaSL/DPFManager#393]
Use clearer naming, tooltip or wiki to clarify elements

**Comment by victormunoz** [comment]
There is already a tooltip in the policy checker.
When you put the mouse over an option, after a second, a tooltip appears.
Does it not work in your case? or you mean that the message should be more detailed?

**Comment by ezellohar** [comment]
Hello, I was the one suggesting Erwin this one.
I see the tooltip, but it's not descriptive of what the rule actually does: for example, for 'pixel density' and 'DPI' rules, the tooltip says, respectively 'pixels per centimeter' and 'dots per inch', but they're not explanatory of what the rules want to set: 'pixels per centimeter' sets a number variable, 'DPI' has only the 'even' or 'uneven' fields selectable, without any tooltip to give a hint of what it means.
What could be useful is a more detailed tooltip to explain what effect will have that rule.

**Comment by victormunoz** [comment]
Yes @ezellohar for sure we can improve the tooltip descriptions. Actually as you have noticed the DPI policy is a bit confusing. It does not check the "dots per inch" value itself but only whether this value is even or odd (this policy was requested by one memory institution). We will clarify the descriptions in the next release.
