### ISSUE TITLE
niso link broken?

### ISSUE THREAD

**Issue by stijndegroof** [EasyinnovaSL/DPFManager#398]
I try to find information about the nisoContainer used in the METS file, but cannot find any. The link provided in mets description seems a good place to start, but it seems broken.

`xmlns:niso="http://www.loc.gov/mix/v20"`
-> goes to [Page Not Found](http://www.loc.gov/mix/v20)

**Comment by stijndegroof** [comment]
Is this the correct link?
https://www.loc.gov/standards/mix/

**Comment by XaviTarres** [comment]
The xmlns:niso="http://www.loc.gov/mix/v20" is not a real link.  the xmlns label defines a namespace, this namespace should match with the namespace declared in the niso XML schema validation file.

Using the namespace as a link to the documentation page is a common practice but unfortunally the www.loc.gov has moved the information.

**Comment by stijndegroof** [comment]
Okay, thanks for the clarification. 
Is this the niso XML schema validation file? http://www.loc.gov/standards/mix/mix.xsd

Apparently, in an earlier version the namespace was "http://www.loc.gov/mix/", which is also a working link, but okay.

(([Test MIX document instance (version 0.2)](http://www.loc.gov/standards/mix/instances/mix_test.xml) contains `xmlns="http://www.loc.gov/mix/"` but [MIX Schema Version 2.0 (current version)](http://www.loc.gov/standards/mix/mix.xsd) contains `xmlns="http://www.loc.gov/mix/v20"`)

**Comment by XaviTarres** [comment]
Yes the current XML shema validation is http://www.loc.gov/standards/mix/mix.xsd

We are going to update the mets report in order to include the  XML schema url. 
I have open a new issue #399

**Comment by stijndegroof** [comment]
Thanks
