### ISSUE TITLE
Allow recursive directory processing (CLI)

### ISSUE THREAD

**Issue by cweigel** [EasyinnovaSL/DPFManager#40]
I recognized that

1.2.1 does not process directories at all
while commit d7b7c64 does

yet, it would be cool if you could specify either a -r option or a depth option that lets the user specify how deep directories are parsed for tif files.

**Comment by victormunoz** [comment]
Yes, a -r option would be useful for CLI.
However, we have to see how to put it also in the GUI (our idea is that both CLI and GUI should have the same options).
Thanks for the feedback!
