### ISSUE TITLE
Threads option (-t) in command line not working

### ISSUE THREAD

**Issue by jamesmooneybodleian** [EasyinnovaSL/DPFManager#404]
When attempting to set the number of threads in DPFManger v3.2 via the command line on linux using the -t option, it reports:

Unknown option: -t
Usage: dpf-manager check [options] source1 [source2 ... sourceN]
(the sources can be single files, directories, zip files or URLs)

Options:
    -c, --configuration <filename>:        Selects a configuration file.
    -f, --format [xml, json, pdf, html]:   Specifies the report format (overridi
    -h, --help:                            Shows this screen.
    -o, --output <path>:                   Specifies the output folder (overridi
    -r, --recursive [depth]:               Check directories recursively. If no
    -s, --silence:                         Silent execution (do not open the rep
    -t, --threads <N>:                     Specify maximum number of threads use
    -w, --overwrite:                       Overwrites the output folder.

**Comment by victormunoz** [comment]
This bug will be solved in the next monthly release.
Thank you very much for reporting!

**Comment by jamesmooneybodleian** [comment]
Ah excellent news. Thanks Victor!
