### ISSUE TITLE
Progress bar in UI for processing

### ISSUE THREAD

**Issue by cweigel** [EasyinnovaSL/DPFManager#44]
Having a progress bar during processing would be great when processing directories with many files.

<img src="https://cloud.githubusercontent.com/assets/13655319/11186207/ec3aace2-8c80-11e5-9178-38e01b882c76.png" width="50%">

**Comment by victormunoz** [comment]
Sure, as well as an estimation of the time to finish.
It is another one of the tasks in the redesign phase we are now working on.
