### ISSUE TITLE
DPF Manager 3.3 throws IFH-003

### ISSUE THREAD

**Issue by PhillipTommerholt** [EasyinnovaSL/DPFManager#445]
Today I tested my first TIFF file with DPF Manager 3.3.
The tools throws an "IFH-003 error" for Baseline 6.0 requirement which states that there should be Little or Big Endian byte order.
When I open the TIFF file with a hexeditor (HxD) the first two hex values are 4949, so I guess there is a problem in the tool and not the TIFF file I tested?

Best regards
Phillip Tømmerholt
The Danish National Archives

**Comment by victormunoz** [comment]
Hello! Thank you for using the DPF Manager.
Of course this error should not appear if the file starts with `4949`.
Can you send us the file?

Which operating system are you using, and which version did you install (lite, 32bits, 64bits)?

Do you get the same result with the online validator?
http://dpfmanager.org/application.html

**Comment by PhillipTommerholt** [comment]
Thanks for the quick response.
Unfortunately I can't share the file because it holds sensitive information, and therefore I can't use the online validator either.
I downloaded the 64bits for Windows - We run Windows 7 Entreprise. I will see if I can dig further and maybe reproduce.

**Comment by victormunoz** [comment]
Ok, can you send me a screenshot of the first lines as seen in the Hexeditor?

**Comment by PhillipTommerholt** [comment]
Yes, here: 
![tiff](https://user-images.githubusercontent.com/15984159/27067443-45b8a950-500b-11e7-91f2-7fe96146a41a.PNG)
I can open the TIFF file with IrfanView and I can't see anything wrong with it. It is rather big, almost 10.000 pages and 2,09GB

**Comment by victormunoz** [comment]
Ok. I have been able to reproduce the issue.
The problem occurs with files of size larger than 2GB (the class that we use to read the file has this restriction). We will try to find a fix for this as soon as possible.
Thank you very much for raising this.

**Comment by victormunoz** [comment]
The new release of DPF Manager that solves this bug is now available!
http://dpfmanager.org
