### ISSUE TITLE
UI and CLI hangs without viewable reason

### ISSUE THREAD

**Issue by cweigel** [EasyinnovaSL/DPFManager#45]
System: Windows 7, Java JRE 1.8.0_66 64bit
Version: Commit d7b7c64

Directory processed: [link](../tree/develop/src/test/resources/Colorspace)
Config file contains:

    ISO	Baseline
    ISO	Tiff/EP
    ISO	Tiff/IT
    ISO	Tiff/IT-1
    ISO	Tiff/IT-2
    FORMAT	HTML
    FORMAT	XML
    FORMAT	JSON
    RULE	ImageWidth,>,100
    RULE	ImageHeight,>,100
    FIX	Copyright,Remove Tag,
    FIX	ImageDescription,Add Tag,New Description

**Comment by cweigel** [comment]
Might be a very slow processing speed. If so issue #44 becomes even more important!

**Comment by victormunoz** [comment]
When selecting a remote URL to process, this option is intended to be a link to a single tif file, not an html page.

**Comment by victormunoz** [comment]
However, of course, the application should show a warning message, not hanging...
