### ISSUE TITLE
missing METS reports

### ISSUE THREAD

**Issue by archivist-liz** [EasyinnovaSL/DPFManager#461]
I ran a folder with 1000+ TIFFs though DPF Manager and noticed that no mets.mxl files were there for some of the images (only the regular xml files). I tried running some of those images individually in DPF Manager, and I still did not get a METS file. (I am using Version 3.2.1 because my organization does not give me permissions to download and install executable files without a hassle, so maybe this wouldn't happen in the latest version?) I am also not sure whether this is an issue with my images or with DPF Manager. Thanks!

**Comment by victormunoz** [comment]
Yes, we are aware of an issue about that: #447
When the TIFF file contains errors, in some cases the METS report is not generated.
We will fix this issue in the next monthly release, so we recommend you tu upgrade once the verison 3.5 is launched (at the end of this month).
Thank you for writting us!

**Comment by archivist-liz** [comment]
Thanks! Do you know what errors in the TIFF file causes this? I am working with an outside vendor and trying to catch anything that isn’t working right. Thanks!

**Comment by victormunoz** [comment]
Many errors in the TIFF file can cause the METS report to be not generated.
You can see the full list of errors of the TIFF files with the other report formats (HTML for example).
Or, if you send me the file, I can examine it.

**Comment by victormunoz** [comment]
If there are no errors in the TIFF, then the METS should be generated.
Please send me the file so we can analyze what is happening.

You can send the TIFF file using this tool: https://wetransfer.com/
My email address is victormunoz@easyinnova.com

Thank you very much for your feedback!

**Comment by archivist-liz** [comment]
I sent the file, did you receive it? Thanks!

**Comment by victormunoz** [comment]
No, I haven't received it.
Maybe it is too big. Can you use the tool I mentioned before?

**Comment by archivist-liz** [comment]
e.kata@iaea.org sent you some files

1 file, 2.8 MB in total
・ Will be deleted on 28 July, 2017


Download link:
https://wetransfer.com/downloads/ba3b17da8c76e21d9441a80a657deeb020170721130427/b17c499746df559b9417a9bebc819ecf20170721130427/cbbcfc


Message:
Tiff with possible errors -- no METS report generated.



1 file

B0055-017.tif


Get more out of WeTransfer, get [Plus](https://wetransfer.com/plus?trk=WT201704_email&utm_campaign=WT_email_tracking&utm_content=general&utm_medium=plus_footer_ad_link&utm_source=notify_recipient_email)



About WeTransfer: https://wetransfer.com/about
Help: https://wetransfer.zendesk.com/hc/en-us
Legal: https://wetransfer.com/legal


To make sure our emails arrive, please add noreply@wetransfer.com to [your contacts](https://wetransfer.zendesk.com/hc/en-us/articles/204909429).

**Comment by archivist-liz** [comment]
I sent the file via WeTransfer. In case you didn’t get the mail with the download link, here it is: https://wetransfer.com/downloads/ba3b17da8c76e21d9441a80a657deeb020170721130427/547f56

Thanks!

**Comment by victormunoz** [comment]
Ok, I have checked it. The image does not have any error regarding baseline, but it has an error with the "extended baseline" reference, related to the tag TransferRange, which has an invalid type.
With the newest version of DPF Manager, the METS report is generated, so it seems that the bug is now solved.
I will send you by email the METS report.
Thanks again for your feedback! We appreciate it!

**Comment by archivist-liz** [comment]
Thank you so much for your help with this! I will make sure to download the current version of DPF Manager promptly. And I am very much looking forward to the 3.5 version. Thanks for all your work on this project – it is really great!

Best regards,
Liz
