### ISSUE TITLE
Specification reference in error OFFSET-0001

### ISSUE THREAD

**Issue by marhop** [EasyinnovaSL/DPFManager#503]
Hi,

Using DPF Manager 3.5.1 I got error OFFSET-0001 (bad word alignment in offset) in a TIFF file because of an odd pointer in an IFD entry. While that's totally correct, here comes the nit-picky part:

The explanation of the error offered by DPF Manager, "the byte offset may refer at any location in the file after the Image File Header (IFH) but must begin on a word boundary" references the TIFF 6 specification, page 13. However, strictly speaking, this very condition only applies to the IFD pointer in the image file header (the pointer to the first IFD), not to pointers in IFD entries.

The equivalent condition for pointers in IFD entries can be found on page 15: "The Value is expected to begin on a word boundary; the corresponding Value Offset will thus be an even number."

So while the error condition is essentially the same (odd pointer) it needs two different references to the spec. (Or alternatively two different errors depending on where the odd pointer occurs.) I know this is a little pedantic, but being pedantic is what validation is all about, isn't it? ;-)

Best,
Martin

**Comment by victormunoz** [comment]
Yes sure!
This should be changed in the implementation checker:
https://github.com/EasyinnovaSL/TIFF-Implementation-Checker

In this file:
https://github.com/EasyinnovaSL/TIFF-Implementation-Checker/blob/master/src/main/resources/implementationcheckers/TIFF_Baseline_Core_6_0.xml
