### ISSUE TITLE
List of validation errors?

### ISSUE THREAD

**Issue by marhop** [EasyinnovaSL/DPFManager#505]
Hi,

Is a list of all validation errors with IDs, descriptions and possible locations available somewhere, either in documentation or in source code? I could not find one ...

Thanks,
Martin

**Comment by victormunoz** [comment]
Yes! The reference documentation is shown here:
http://dpfmanager.org/reference-documentation.html

And the source code is here:
https://github.com/EasyinnovaSL/TIFF-Implementation-Checker

**Comment by marhop** [comment]
Great, thank you! That's perfect.
