### ISSUE TITLE
DPFManager does not store full file path in reports

### ISSUE THREAD

**Issue by pieterdp** [EasyinnovaSL/DPFManager#83]
When creating a report, DPFManager only stores the filename in the report, but not the full path of the file. When recursing through a directory, this makes it very hard to almost impossible to match a report with a file, as multiple files with the same name may be present.

Storing the full path of the file would prevent this problem.

**Comment by victormunoz** [comment]
Yes, that's true. We will work on this for the next update. Thanks for your comment!
