### ISSUE TITLE
DPFManager ignores -o flag when the parent folder does not exist

### ISSUE THREAD

**Issue by pieterdp** [EasyinnovaSL/DPFManager#84]
When you use the -o flag with a folder (e.g. /foo/bar/biz) and the parent folder does not exist (e.g. /foo/bar), it ignores the flag and uses the default output directory. The user executing the application has the necessary rights to create the parent folder.

The application should create the entire path if it can and should error when it can't.

**Comment by victormunoz** [comment]
It will. Thanks for your feedback!
