### ISSUE TITLE
DPFManager hangs when checking folders containing >500 files

### ISSUE THREAD

**Issue by pieterdp** [EasyinnovaSL/DPFManager#86]
If a folder contains a lot of files (from testing that seems to above 450-550), the GUI of DPF Manager hangs. There is no indication of progress and no reports are being created.

We're running this on a Mac Mini with OS X 10.11.2, 4GB of RAM and JDK 8u66.

What could be the cause of this?

**Comment by victormunoz** [comment]
I've made tests with folders containing near 1000 files without problems, so I guess the problem is not related with the number of files, but caused by the files itself (or one of the files). Can you reproduce the problem with less files?

However, it is strange that no progress indication is shown. At least the message "Processing...1/550" should be displayed. Are you using version 1.3 or higher?

**Comment by pieterdp** [comment]
I haven't been able to. The message "Processing " does appear, but around number 540, it simply hangs and stops checking. I've checked the file it hangs on, and the does not seem to have any issues (not corrupt, not 0B etc.).

The folders are located on a Samba share, perhaps that could be the issue? I'll try to check with a local folder some time later today.

**Comment by pieterdp** [comment]
I've been able to test a few things:
* The problem also exists in local folders (not on a remote share).
* It also happens in folders containing less files (153).
* It also happens in a folder containing a lot (2000) of smaller files (<50MB) and in a folder containing few (153) larger files (>50MB).

In all cases, I've checked the files DPF Manager hangs on, and the file displays fine (so it isn't corrupt).

Could this have something to do with exceeding some kind of memory limit?

**Comment by victormunoz** [comment]
Yes, it seems to be some kind of memory leak. We are going to perform some more tests in order to reproduce it

**Comment by Adri7** [comment]
We investigated this issue and as we thought, it's a memory leak. Now we can detect it, and inform the user, so the GUI will not hang anymore.

We will work for reduce the memory usage of DPFManager.

Thank you for telling us the issue!

**Comment by victormunoz** [comment]
A new release of DPF Manager has been publiched right now. It includes fixes for this issue and many more. You can download the latest version at the website http://dpfmanager.org/ The list of changes of this new version can be seen here: https://github.com/EasyinnovaSL/DPFManager/releases
Thank you again for your feedback!
